pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Ahammed-2006/calculator-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Specify Dockerfile path
                    sh 'docker build -t calculator:calculator -f calculator-project/Dockerfile calculator-project/'
                }
            }
        }

        stage('Save Docker Image Locally') {
            steps {
                sh "docker save calculator:calculator -o calculator.tar"
                echo "Docker image saved locally as calculator.tar"
            }
        }
    }
}
