pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/Ahammed-2006/calculator-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t calculator:calculator -f calculator-project/Dockerfile calculator-project/'
            }
        }

        stage('Push to Local Registry') {
            steps {
                script {
                    def hostIP = sh(script: "hostname -I | awk '{print \$1}'", returnStdout: true).trim()
                    sh "docker tag calculator:calculator ${hostIP}:5000/calculator:latest"
                    sh "docker push ${hostIP}:5000/calculator:latest"
                }
            }
        }

        stage('Save Docker Image Locally') {
            steps {
                sh 'docker save calculator:calculator -o calculator.tar'
                echo 'Docker image saved locally as calculator.tar'
            }
        }
    }
}
